server:
  port: 8080

spring:
  application:
    name: ms-pedidos360-bff
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ENTRA_ISSUER_URI:https://login.microsoftonline.com/0bfad962-b91d-465a-b769-8e71565efe7d/v2.0}
          audiences: ${ENTRA_API_CLIENT_ID:d80d5009-1b8a-49b2-a3da-08a8bbd00936}

management:
  endpoints:
    web:
      exposure:
        include: health

pedidos360:
  services:
    connect-timeout: ${SERVICES_CONNECT_TIMEOUT:2s}
    read-timeout: ${SERVICES_READ_TIMEOUT:5s}
    catalog:
      base-url: ${CATALOG_BASE_URL:http://localhost:8081}
  security:
    enforce-roles: ${ENFORCE_ROLES:false}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}

logging:
  pattern:
    level: "%5p [%X{requestId:-}]"
